# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Touch: 1

version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/content/Ddth/.github/workflows"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "nuget"
    directories:
      - "/content/Ddth/Ddth.Mylib"
      - "/content/Ddth/Ddth.Mylib.Tests"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "**"
        update-types: ["version-update:semver-major"] # do not update to major version as it may contain breaking changes
